spring.application.name=stk-push

server.port=8082

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/stk_db
spring.datasource.username=root
spring.datasource.password=hezron
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Daraja Sandbox Credentials
daraja.consumer-key=vVqRlmYzzHezzqBFfzr8FpbLtjTaB0zxyve2TAVwNiOp6BeH
daraja.consumer-secret=ZFHocgXesDx5RjYLDF30hvD3jM4SVEZGRnOFQeXVCfTnMRL7jomqOIKkDJ0yyCqe
daraja.shortcode=174379
daraja.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
daraja.callback-url=https://your-callback-url.com/api/mpesa/callback
daraja.auth-url=https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
daraja.stk-push-url=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest